name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install coverage
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        python utils/lint.py --path ./linter --threshold 2
    - name: Analysing the code coverage
      run: |
        python utils/coverage.py --path ./linter --threshold 80
        coverage report -m
